version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo-energy
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-energy
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - grafana_data:/var/lib/grafana
    

    

volumes:
  mongo_data:
  grafana_data:

#Se crea un contenedor mongo-energy con MongoDB, puerto 27017 abierto
#Se crea un contenedor grafana-energy con Grafana, puerto 3000 abierto
#Se usa volumenes para que los datos/config no se pierdan por si llegamos a apagar los contenedores
#En la terminal del proyecto usar el comando "docker-compose up -d" para levantar los contenedores en segundo plano con docker 
# abierto, por cualquier cosa... jajaja
